POST http://localhost:3000/messages
Content-Type: application/json

{
    "title": "Teste 9871212",
    "text": "Test Text 65",
    "recipients": ["teste@teste.com","teste2@teste.com"],
    "invalidField": "invalid field test"
}

###
GET http://localhost:3000/messages
Content-Type: application/json

###
GET http://localhost:3000/messages/60ad4618373af5e0734d372e
Content-Type: application/json

